### ISSUE TITLE
url:er

### ISSUE THREAD

**Issue by SheriefBadran** [ib222dp/1DV450_ib222dp#12]
Jag tycker det skulle vara tydligare om man kunde fråga api:et om attractions på en viss tagg på formatet /attractions/:taggName eller /tags/:id/attractions. I så fall hade man exempelvis fått ut enbart tags då man gör frångan /tags. Nu får man med attractions på url:en /tags vilket också är helt ok. Tänker bara som ett tips om man vill bredda utbudet och tydligheten något.

**Comment by ib222dp** [comment]
Nu går det att göra anropet /tags/:id/attractions i API:et. Man får fortfarande med attractions när man anropar /tags, eftersom man i klienten ska kunna se vilka attractions som varje tag har.
