### ISSUE TITLE
Statuskoder

### ISSUE THREAD

**Issue by SheriefBadran** [ib222dp/1DV450_ib222dp#13]
Statuskoderna ser bra ut, förutom i två fall som jag blir lite tveksam till.
1. När jag försöker uppdatera en resurs som inte finns (med fel id), får jag tillbaka statuskod 204. Jag tycker det borde vara en 400. När jag uppdaterar på rätt sätt får jag fortfarande tillbaka statuskod 204. Jag förstår inte riktigt varför eftersom du i action-metoden update faktiskt sätter statuskod 200.
2. Om jag gör en get på exempelvis attractions och inte skickar med en api nyckel tycker jag att jag borde få tillbaka statuskod 401 med en WWW-Authenticate header satt till Token realm = "Attractions". På så sätt framgår det i svars-headern vilken resurs som skyddas.

**Comment by 1dv450** [comment]
:+1: Bra feedback!

**Comment by ib222dp** [comment]
1. Nu har jag ändrat update-metoden så att det blir en 400 när man försöker uppdatera en resurs som inte finns, och en 200 samt att den uppdaterade resursen returneras när man uppdaterar på rätt sätt.
2. Jag har ändrat så att man får tillbaka en WWW-Authenticate header nu.
