### ISSUE TITLE
API-nyckel för create update och delete?

### ISSUE THREAD

**Issue by SheriefBadran** [ib222dp/1DV450_ib222dp#14]
Jag är inte säker på detta men jag funderar på om inte api-nyckeln borde skickas med även för create, update och delete?

**Comment by 1dv450** [comment]
Jo, api-nyklen ska ingå i alla anrop. Tänk att den används för att hålla reda på statistik där alla anrop bör ingå.

**Comment by ib222dp** [comment]
Jag har ändrat så att API-nyckeln måste skickas med vid varje anrop.
