### ISSUE TITLE
Kod

### ISSUE THREAD

**Issue by SheriefBadran** [ib222dp/1DV450_ib222dp#15]
User klassen bör validera valid email med presence true eftersom det krävs vid login.

**Comment by SheriefBadran** [comment]
Koden ser ok ut, hittar inget att anmärka på förutom en sak. I exempelvis attractions_controller finns det flera ställen i metoderna update och delete där du kollar om user = nil och om tag = nil. Om de är nil så skapar du ett felmeddelande. Vad jag förstår så kommer aldrig koden i if-satserna att köras eftersom du med endast ett '=' tecken tilldelar user och tag värdet nil, och eftersom att nil ger false i if-satsen så kommer aldrig koden i if-satserna att exekveras. De delarna av koden blir därför död kod.

**Comment by ib222dp** [comment]
Jag lade inte till någon validering i user-klassen eftersom man i min applikation inte kan skapa några nya users. Från railsguides: "Validations are used to ensure that only valid data is saved into your database".

Jag har skrivit om update och destroy-metoderna och tagit bort den koden du nämner.
