### ISSUE TITLE
Sammanfattning

### ISSUE THREAD

**Issue by SheriefBadran** [ib222dp/1DV450_ib222dp#16]
Helhetsuppfattningen är positiv! Tycker att du uppfyller kraven och har gjort ett bra jobb! Jag har anmärkt på en del saker som du kan se som tips eller småfix. När jag läser din kod upptäcker jag saker jag själv har glömt :) Hoppas du får någon nytta av min feedback!

**Comment by ib222dp** [comment]
Tack för det, och tack för bra feedback!
