### ISSUE TITLE
Sammanfattning

### ISSUE THREAD

**Issue by 1dv450** [ib222dp/1DV450_ib222dp#17]
Jag har kollat igenom APIet.
På det hela taget verkar det fungera men jag har några kommentarer och saker jag inte får att fungera.
- Det är ganska få länkar i dina response. Här hade man kunnat jobba på med lite fler till fela delar av API:et i sina response
  *När man frågar efter en attraction finns inte dess tags med. Det borde man kunna få ut i ett och samma anrop. När man frågar efter tags så listas attraktionera däremot.
- Jag får en 500 tillbaka när jag försöker skapa en attraktion med din Postman-fil
- När jag uppdaterar får jag en 204 tillbaka vilket indikerar att det gått bra (kan iofs tycka att man bör få tillbaka resursen så man ser att den blivit uppdaterad). När jag sedan gör en GET på denna uppdaterade resurs så verkar den inte ha ändrats? Bugg?
- Implementationen av JWT verkar tämligen copy och paste från mina exempel vilket gör att du fått med onödig kod.

**Comment by ib222dp** [comment]
1. Nu får man även med tags när man anropar en attraction.
2. Jag har skapat en ny Postman-fil och lagt upp den på GitHub. Det gick bra för mig att skapa en ny attraction i den nya filen.
3. Nu får man 200 tillbaka och den uppdaterade resursen, och resursen har ändrats när man gör en GET på den.
4. Jag har tagit bort den onödiga koden.
