### ISSUE TITLE
client: Applikationen

### ISSUE THREAD

**Issue by SheriefBadran** [ib222dp/1DV450_ib222dp#18]
Applikationen verkar inte vara helt färdig ännu, jag blev lite förvirrad över hur applikationen är tänkt att fungera. I inloggat läge ser jag bara de attractions jag själv skapat + globen? När jag är utloggad ser jag alla attractions. Jag tror att jag sedan förstod din tanke, nämligen att man i inloggat läge ska kunna se och administrera (redigera och ta bort) attractions man själv skapat.

Det tycker jag är helt ok, men då kanske det ska finnas ett menyval för att se och administrera attractions man själv skapat då man är inloggad, men även kunna se alla andra attractions.

Angular är ju bra på just sådana saker som att anpassa en meny till olika states/lägen i en applikation.

För att ge lite handfasta tips på hur man kan göra en sådan sak skapade jag ett repo [Proposal](https://github.com/SheriefBadran/Proposal) där jag lade in din klientkod med ett förslag på hur det skulle kunna se ut. Om du vill kan du kolla på det. I readme filen har jag listat vilka filer jag ändrat i samt en kommentar till det. Jag har även kommenterat vad jag gjort i koden. Detta får också bli lite som en kommentar på din kod. Jag tycker nämligen din kod ser bra ut förutom att du lite missar att använda angular till det som det är bra på. Förändringarna kanske kan vara till nytta för att lösa andra problem i applikationen. Jag har testat att mina tips fungerar.

Övrigt:
- Riktigt bra att du undviker strängberoenden genom att sätta konstanter i app.js.
- LoginCtrl borde använda en service för att posta logindata istället för att göra en $http.post direkt i kontrollen.

**Comment by ib222dp** [comment]
Tack så mycket för din exempelkod! Jag tyckte det såg bra ut, så jag har lagt in det i min kod. Jag lade också till "if $rootScope.isLoggedIn" i metoderna där man hämtar, skapar, ändrar och tar bort sina egna turistattraktioner, och jag har ändrat så att det nu också finns en LoginService.
