### ISSUE TITLE
Applikation

### ISSUE THREAD

**Issue by mf222nb** [ib222dp/1DV450_ib222dp#2]
Hej!

Jag har nu kollat igenom koden som jag fick och den är bra skriven och lätt att se vad allt gör, hade väll gärna sett lite kommentarer så hade det varit ännu lättare att förstå.

Applikationen fungerar som det är tänkt utom på en grej som jag tar upp precis nedanför som är en viktigt för Admin.

Ett fel som jag har upptäckt är att när jag skapar en ny användare och fått en nyckel och sedan loggar in som Admin så har jag inte den nya amvändarens nyckel i listan. Jag har kontrollerat så att den finns i databasen och det gör den och jag kan se den om jag loggat in som den ny-skapade användaren men kan inte se den i listan för Admin.

En sak till som du kan lägga till i din readme.me, detta är inget nödvändigt men sparar en del tid om man sitter på Windows och det är att om man sitter i Windows och har till exempel RubyMine som utvecklingsmiljö så kan man inte köra rake db:migrate direkt när man har laddat ner applikationen. Det man måste göra då är att öppna Gemfile och lägga till denna rad 
gem 'tzinfo-data'
och sedan köra en bundle install i terminalen.

**Comment by ib222dp** [comment]
Hej,
Jag har lagt till det du nämnde i readme-filen.
Det du skriver om Admin tas upp i en annan issue som jag har fått, så jag stänger denna issue.
Tack för feedback!
