### ISSUE TITLE
client: Autentisering

### ISSUE THREAD

**Issue by SheriefBadran** [ib222dp/1DV450_ib222dp#20]
Jag blir utloggad lite då och då. Det känns som om jag blir utloggad när jag klickar på Home i menyn. Det blir lite svårt att se om jag är inloggad eller inte när det inte finns en knapp för att logga ut.

Ett annat problem är att appUser med api-nyckel och inloggad user i klientapplikationen är samma användare. Vad jag förstått det som ska man skilja på applikationen som en användare av api:et och slutanvändaren av själva klientapplikationen.

**Comment by ib222dp** [comment]
Jag tog bort kodraden "$rootScope.isLoggedIn = false" överst i LoginController, vilken var orsaken till att man blev utloggad när man klickade på Home i menyn. Jag har också lagt till en Logga ut-knapp, och tack vare din ändring i menyn så försvinner nu "MyAttractions" ur menyn när man är utloggad, så det blir tydligare om man är inloggad eller inte.

Jag har tagit bort apikey som egenskap från user och skapat klassen apiuser med egenskapen apikey i API:et.
