### ISSUE TITLE
client: Attractions och tags

### ISSUE THREAD

**Issue by SheriefBadran** [ib222dp/1DV450_ib222dp#23]
Om jag klickar på more info för en attraction så förväntar jag mig att se mer information om den turistattraktionen. Jag ser bara en rubriken tags. Däremot om jag klickar på Tags i menyn så får jag en lista med alla tags, om jag då klickar på "more info" om en tag så får jag en attraction för den taggen. Jag tycker att du ska visa lite information om turistattraktionen man valt att läsa mer om samt vad den har för taggar.

**Comment by ib222dp** [comment]
Jag hade lite problem med att lista både alla attractions en tagg har och alla taggar en attraction har. Det fungerar inte med att ha include i både attraction och tag eftersom det verkar leda till en infinite loop.
Nu har jag i alla fall ändrat i show-metoden i attractions_controller, från "respond_with attraction" till  "render json: @attraction, :include => :tags", så nu kan man se alla taggar en attraction har när man klickar på More info.
