### ISSUE TITLE
client: Omladdning av en sida

### ISSUE THREAD

**Issue by SheriefBadran** [ib222dp/1DV450_ib222dp#24]
Om jag när som helst i applikationen laddar om en sida försvinner allt innehåll.

**Comment by ib222dp** [comment]
Jag har löst det nu genom att kopiera allt innehåll i index.html till en fil som heter 404.html. 
(http://stackoverflow.com/questions/17912543/getting-404-page-on-refresh-on-angularjs-site)
Vet inte om det är en bra lösning men det var enkelt och det fungerar i alla fall.

**Comment by 1dv450** [comment]
Bästa lösningen är ju det vi diskuterade kring deep-linking. Men det var inget krav.
