### ISSUE TITLE
client: Kartan

### ISSUE THREAD

**Issue by SheriefBadran** [ib222dp/1DV450_ib222dp#25]
Det skulle vara till stor fördel för kartan om varje marker har en label eller infowindow så att man kan se vilken attraction en marker motsvarar.

**Comment by ib222dp** [comment]
Jag håller med om att det skulle öka användarvänligheten, men i nuläget nöjer jag mig med att man åtminstone kan se vilken attraction markern motsvarar när man hovrar över den.
