### ISSUE TITLE
Kommentarer

### ISSUE THREAD

**Issue by 1dv450** [ib222dp/1DV450_ib222dp#8]
Hej!

Du har fått lite kommentarer från dina peers som jag kan stämma in i. Speciellt #6 och #7 Där sista issuen ger ett säkerhetshål. Som inloggad användare kan man komma åt och ta bort andra användares nycklar genom att ändra id i urlen: http://localhost:3000/user_revoke_key?apikey=2
Dina routes följer inte riktigt ramverkets filosofi kring rest men det kommer vi ju jobba mer kring i API-delen.
Man skulle som admin också kunna ta bort användares nycklar. Nu känns admin mer som en vanlig användare?
Jag hade nog också slagit ihop sidorna där man visar apinycklen och sidan med en tabort-knapp. Känns som en användare som loggar in kommer till en och samma sida där både nycklen och tabort-knappen finns.

Annars tycker jag koden är tydlig och enkel då den följer ramverkets struktur. Bra kommentarer där det behövs.

Komplettera issue #6 och #7 och stäng sedan denna bugg-kommentaren.

**Comment by ib222dp** [comment]
Jag har åtgärdat #6 och #7 och stängt dem.

**Comment by 1dv450** [comment]
:+1:
